/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignUpImport } from './routes/sign-up'
import { Route as OauthCallbackImport } from './routes/oauth-callback'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardUserImport } from './routes/dashboard/$user'
import { Route as DashboardCheckIndexImport } from './routes/dashboard/check/index'
import { Route as DashboardCheckIdImport } from './routes/dashboard/check/$id'

// Create/Update Routes

const SignUpRoute = SignUpImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const OauthCallbackRoute = OauthCallbackImport.update({
  id: '/oauth-callback',
  path: '/oauth-callback',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardUserRoute = DashboardUserImport.update({
  id: '/dashboard/$user',
  path: '/dashboard/$user',
  getParentRoute: () => rootRoute,
} as any)

const DashboardCheckIndexRoute = DashboardCheckIndexImport.update({
  id: '/dashboard/check/',
  path: '/dashboard/check/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardCheckIdRoute = DashboardCheckIdImport.update({
  id: '/dashboard/check/$id',
  path: '/dashboard/check/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/oauth-callback': {
      id: '/oauth-callback'
      path: '/oauth-callback'
      fullPath: '/oauth-callback'
      preLoaderRoute: typeof OauthCallbackImport
      parentRoute: typeof rootRoute
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/$user': {
      id: '/dashboard/$user'
      path: '/dashboard/$user'
      fullPath: '/dashboard/$user'
      preLoaderRoute: typeof DashboardUserImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/check/$id': {
      id: '/dashboard/check/$id'
      path: '/dashboard/check/$id'
      fullPath: '/dashboard/check/$id'
      preLoaderRoute: typeof DashboardCheckIdImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/check/': {
      id: '/dashboard/check/'
      path: '/dashboard/check'
      fullPath: '/dashboard/check'
      preLoaderRoute: typeof DashboardCheckIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard/$user': typeof DashboardUserRoute
  '/dashboard/check/$id': typeof DashboardCheckIdRoute
  '/dashboard/check': typeof DashboardCheckIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard/$user': typeof DashboardUserRoute
  '/dashboard/check/$id': typeof DashboardCheckIdRoute
  '/dashboard/check': typeof DashboardCheckIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard/$user': typeof DashboardUserRoute
  '/dashboard/check/$id': typeof DashboardCheckIdRoute
  '/dashboard/check/': typeof DashboardCheckIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/oauth-callback'
    | '/sign-up'
    | '/dashboard/$user'
    | '/dashboard/check/$id'
    | '/dashboard/check'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/oauth-callback'
    | '/sign-up'
    | '/dashboard/$user'
    | '/dashboard/check/$id'
    | '/dashboard/check'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/oauth-callback'
    | '/sign-up'
    | '/dashboard/$user'
    | '/dashboard/check/$id'
    | '/dashboard/check/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  SignUpRoute: typeof SignUpRoute
  DashboardUserRoute: typeof DashboardUserRoute
  DashboardCheckIdRoute: typeof DashboardCheckIdRoute
  DashboardCheckIndexRoute: typeof DashboardCheckIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  SignUpRoute: SignUpRoute,
  DashboardUserRoute: DashboardUserRoute,
  DashboardCheckIdRoute: DashboardCheckIdRoute,
  DashboardCheckIndexRoute: DashboardCheckIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/oauth-callback",
        "/sign-up",
        "/dashboard/$user",
        "/dashboard/check/$id",
        "/dashboard/check/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/oauth-callback": {
      "filePath": "oauth-callback.tsx"
    },
    "/sign-up": {
      "filePath": "sign-up.tsx"
    },
    "/dashboard/$user": {
      "filePath": "dashboard/$user.tsx"
    },
    "/dashboard/check/$id": {
      "filePath": "dashboard/check/$id.tsx"
    },
    "/dashboard/check/": {
      "filePath": "dashboard/check/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
